---
- community.general.discord:
    webhook_id: "{{ lookup('env', 'DISCORD_ID') }}"
    webhook_token: "{{ lookup('env', 'DISCORD_TOKEN') }}"
    content: "StepCA Certificate Authority: Beginning role deployment... "

- community.general.discord:
    webhook_id: "{{ lookup('env', 'DISCORD_ID') }}"
    webhook_token: "{{ lookup('env', 'DISCORD_TOKEN') }}"
    content: "StepCA Certificate Authority: Installing dependencies... "
  tags: install_dependencies

- name: Install dependencies
  ansible.builtin.include_tasks:
    file: "install_dependencies.yml"
  tags: install_dependencies

- community.general.discord:
    webhook_id: "{{ lookup('env', 'DISCORD_ID') }}"
    webhook_token: "{{ lookup('env', 'DISCORD_TOKEN') }}"
    content: "StepCA Certificate Authority: Creating Service Users... "
  tags: create_serviceuser

- name: Add Service User
  ansible.builtin.include_tasks:
    file: "create_serviceuser.yml"
  tags: create_serviceuser

- community.general.discord:
    webhook_id: "{{ lookup('env', 'DISCORD_ID') }}"
    webhook_token: "{{ lookup('env', 'DISCORD_TOKEN') }}"
    content: "StepCA Certificate Authority: Pulling Github Tag... "
  tags: install_smallstep

- name: Get the latest tag from Github for Smallstep CA Step utility
  ansible.builtin.uri:
    url: https://api.github.com/repos/smallstep/cli/releases/latest
  register: latest_release
  tags: install_smallstep

- name: Get version from file
  ansible.builtin.shell:
    cmd: "test -f \"{{ installed_version_path }}\" && cat {{ installed_version_path }}"
  register: installed_version
  failed_when: false
  changed_when: false
  tags: install_smallstep

- name: Print installed_version
  ansible.builtin.debug:
    msg: "{{ installed_version }}"
    verbosity: 0

- name: Print tag_name
  ansible.builtin.debug:
    msg: "{{ latest_release.json.tag_name }}"
    verbosity: 0

- name: Print comparison
  ansible.builtin.debug:
    msg: "{{ installed_version.stdout != latest_release.json.tag_name }}"
    verbosity: 0

- community.general.discord:
    webhook_id: "{{ lookup('env', 'DISCORD_ID') }}"
    webhook_token: "{{ lookup('env', 'DISCORD_TOKEN') }}"
    content: "StepCA Certificate Authority: Installing StepCA... "
  tags: install_smallstep

- name: Install Smallstep CA if needed
  ansible.builtin.include_tasks:
    file: "install_stepca.yml"
  when: (installed_version.stdout != latest_release.json.tag_name)
  tags: install_smallstep

- name: Check if CA initialized
  ansible.builtin.stat:
    path: "{{ ca_config_location }}"
  register: ca_initiated
  tags: initiate_ca

- community.general.discord:
    webhook_id: "{{ lookup('env', 'DISCORD_ID') }}"
    webhook_token: "{{ lookup('env', 'DISCORD_TOKEN') }}"
    content: "StepCA Certificate Authority: Initializing StepCA... "
  tags: initiate_ca

- name: Initialize Smallstep CA if needed
  ansible.builtin.include_tasks:
    file: "init_stepca.yml"
  when: not ca_initiated.stat.exists
  tags: initiate_ca

- name: Check if service file installed
  ansible.builtin.stat:
    path: "{{ step_service_location }}"
  register: service_deployed
  tags: deploy_service

- community.general.discord:
    webhook_id: "{{ lookup('env', 'DISCORD_ID') }}"
    webhook_token: "{{ lookup('env', 'DISCORD_TOKEN') }}"
    content: "StepCA Certificate Authority: Installing Service... "
  tags: deploy_service

- name: Install Service File if needed
  ansible.builtin.include_tasks:
    file: "install_service.yml"
  when: not service_deployed.stat.exists
  tags: deploy_service






- community.general.discord:
    webhook_id: "{{ lookup('env', 'DISCORD_ID') }}"
    webhook_token: "{{ lookup('env', 'DISCORD_TOKEN') }}"
    content: "StepCA Certificate Authority: Complete! "